### ISSUE TITLE
Preparing commit dialog failed

### ISSUE THREAD

**Issue by yahyaKacem** [brackets-userland/brackets-git#1020]
I just click the commit button.

---

_Brackets 1.3.0-16022 (linux), Git 1.9.1 & Brackets-Git 0.14.24_

**Preparing commit dialog failed**

```
Error: error: cannot run exiftool: No such file or directory
fatal: unable to read files to diff
```

```
call: git diff --no-ext-diff --no-color --staged
Error: error: cannot run exiftool: No such file or directory
fatal: unable to read files to diff
    at Object.exports.toError (file:///home/yahya/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/yahya/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Your `git` is trying to call `exiftool`, but I don't really understand why because theres `--no-ext-diff` parameter there.
