### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by btheobald** [brackets-userland/brackets-git#1055]
For some reason, my installation of git on windows doesn't seem to recognise the options --porcelain or --progress.

_Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27_

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin dev
```

```
call: git push --porcelain --progress origin dev
Error: cmd-spawn-timeout: git push --porcelain --progress origin dev
    at timeoutPromise (file:///C:/Users/Byron/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/Byron/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by iegik** [comment]
#1031
