### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by DiamondeX** [brackets-userland/brackets-git#1089]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

steps was as follows:
1. created new repo in my github account
2. clone it to my local folder through git bash
3. added some files locally
4. created new branch 'trial' in github repo
5(fail). push to newly created brunch through brackets git plugin

---

_Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27_

**Pushing to remote failed**

```
Error: error: src refspec trial does not match any.
error: failed to push some refs to 'https://DiamondeX:***@github.com/DiamondeX/mechanical-like-counter.git'
```

```
call: git push --porcelain --progress origin trial
Error: error: src refspec trial does not match any.
error: failed to push some refs to 'https://DiamondeX:cEduiFUkgQ1ngrfep2qg@github.com/DiamondeX/mechanical-like-counter.git'
    at Object.exports.toError (file:///C:/Users/%D0%A0%D1%83%D1%81%D0%BB%D0%B0%D0%BD/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/%D0%A0%D1%83%D1%81%D0%BB%D0%B0%D0%BD/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by emilz0r** [comment]
Have same error with same steps.

**Comment by DiamondeX** [comment]
Issue is no more relevant
