### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by pankaj-ag** [brackets-userland/brackets-git#1098]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

---

_Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27_

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe push --porcelain --progress --set-upstream origin micro_site
```

```
call: git push --porcelain --progress --set-upstream origin micro_site
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe push --porcelain --progress --set-upstream origin micro_site
    at timeoutPromise (file:///C:/Users/pankaj%20agrawal/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/pankaj%20agrawal/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by iegik** [comment]
#1031
